import React, { PropsWithChildren } from 'react';
import Nav from './Nav';
import Head from 'next/head';
import Header from './Header';
import styled from 'styled-components';
import PixelContainer from '../common/PixelContainer';
import { useRef, useState } from 'react';

const AppLayout: React.FC<PropsWithChildren> = ({ children }) => {
  const HeaderRef = useRef<HTMLDivElement>(null);
  const [headerHeight, setHeaderHeight] = useState<number>(HeaderRef.current?.scrollHeight || 88);

  return (
    <MainContainer headerHeight={headerHeight}>
      <Head>
        <title>PICK ME UP v0.0.1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div ref={HeaderRef}>
        <Header />
      </div>
      {/* <Nav /> */}
      <PixelContainer background="#ffe6bd">
        <section>{children}</section>
      </PixelContainer>
    </MainContainer>
  );
};

const MainContainer = styled.div<{ headerHeight: number }>`
  max-width: 1024px;
  margin: auto;

  section {
    position: relative;
    height: calc(100vh - ${(props) => props.headerHeight}px);
  }

  @media (max-width: 800px) {
    .container {
      width: 100%;
    }
  }
`;

export default AppLayout;
