import React, { PropsWithChildren } from 'react';
import Head from 'next/head';
import Header from './Header';
import styled from 'styled-components';
import PixelContainer from '../common/PixelContainer';
import { useRef, useState } from 'react';
import BgmPlayer from '../common/BgmPlayer';

const AppLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <MainContainer>
      <BgmPlayer />
      <Head>
        <title>PICK ME UP v.0.0.1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PixelContainer background="#ffe6bd">
        <section>{children}</section>
      </PixelContainer>
    </MainContainer>
  );
};

const MainContainer = styled.div`
  max-width: 1024px;
  margin: auto;

  display: flex;
  flex-direction: column;

  section {
    position: relative;
    height: 100vh;
  }
`;

export default AppLayout;
